### ISSUE TITLE
:lady_beetle: Form fields data should be pre-filled from preserved data

### ISSUE THREAD

**Issue by mahabubx7** [fickryiman/fickryiman.github.io#11]
### :lady_beetle: Form fields data should be pre-filled from preserved data #10 

:heavy_check_mark: Form data is preserved in `localStorage`
:heavy_multiplication_x: Form data is not pre-filled from `localStorage`

> You can implement the necessary `javaScript` codes to fetch your preserved data from localStorage by conditions and make it functional for pre-filling the form fields.

**Comment by fickryiman** [comment]
preserved data done
